# ===================================================================
# MONOREPO WORKSPACE CONFIGURATION
# ===================================================================
#
# Configuración de workspace para pnpm que define la estructura
# del monorepo con frontend, API y paquetes compartidos

packages:
  # Aplicaciones principales
  - "apps/api"
  # Temporarily excluding apps/web due to build error
  # - "apps/web"

  # Paquetes compartidos (tipos, utilidades, configuraciones)
  - "packages/*"

  # Directorio raíz para scripts globales
  - "."

# Configuración de dependencias compartidas
catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0

  # TypeScript
  typescript: ^5.0.0

  # Build tools
  vite: ^5.4.8

  # Utilities
  lucide-react: ^0.263.1

  # Backend
  express: ^4.18.0
  cors: ^2.8.5

  # Database
  "@supabase/supabase-js": ^2.0.0
